Mention IBC for TWS/Gateway
Voyz/ibeam pull request #158
Opened 2023-08-30 03:03 UTC by tredondo

2023-08-30 22:55 UTC, tredondo commented
There's also a Docker image project with IB Gateway and IBC, https://github.com/UnusualAlpha/ib-gateway-docker

2023-08-31 18:49 UTC, Voyz requested changes
I appreciate this contribution @tredondo, good idea to mention it here 👏👏👏

2023-08-31 18:49 UTC, Voyz commented on README.md
> +**NOTE**: IBeam is not designed to automate logging into TWS or IB Gateway. Use [IBC](IBC) for that.
Could you change it to 

> ... or IB Gateway (also known as TWS Gateway)

as I heard some people calling it this way?

2023-08-31 18:49 UTC, Voyz commented on README.md
> +[IBC]: https://github.com/IbcAlpha/IBC
just for consistency, I use all-lowercase-with-dashes for link variables. Could you update it?

2023-08-31 22:17 UTC, Voyz commented
Great stuff @tredondo 💪 Thanks!

2023-08-31 22:17 UTC, merged